### PR TITLE
Adds a script to start fileserver for development

### PR DESCRIPTION
**Pull request by Hilbrand**
Starts the fileserver at port 8060

### CODE REVIEW

**Review by JornC — APPROVED** [review]
ACK

**Comment by SerhatG** [comment]
Is this for development of the file-server or to use in other products in general? For the latter I'd advice using the Docker images in Nexus. Way easier. This should help though for the former.

**Comment by JornC** [comment]
> Is this for development of the file-server or to use in other products in general? For the latter I'd advice using the Docker images in Nexus. Way easier. This should help though for the former.

The former, a more elaborate version of https://github.com/aerius/register/blob/main/scripts/misc/fileserver.sh

**Comment by SerhatG** [comment]
Sounds good.. The `register` script can then leverage the Docker variant.

**Review by SerhatG — APPROVED** [review]

**Pull request merged**
